name: Update ReadMe with Commits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update ReadMe
        run: |
          echo "## Solved LeetCode Questions" >> README.md
          ls -d */ >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent commits"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
