name: Update ReadMe with Commits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Folder Names
        id: folder_names
        run: |
          echo "::set-output name=names::$(ls -d */)"

      - name: Update ReadMe
        run: |
          FOLDER_LIST=$(echo "${{ steps.folder_names.outputs.names }}" | awk -F/ '{for (i=1; i<=NF; i++) print "- " $i}')
          if grep -q "## Solved LeetCode Problems" README.md; then
            sed -i '/## Solved LeetCode Problems/,$d' README.md
          fi
          echo "## Solved LeetCode Problems" >> README.md
          echo "${FOLDER_LIST}" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent commits"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
