name: Update ReadMe with Commits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GITHUB_TOKEN environment variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Update ReadMe Content
        run: python update_readme.py
