name: Update ReadMe with Commits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Folder Names
        id: folder_names
        run: |
          FOLDER_LIST=$(ls -d */ | sed 's#/$##')
          echo "FOLDER_NAMES=${FOLDER_LIST}" >> $GITHUB_ENV

      - name: Show Folder Names
        run: |
          echo "Folder names: $FOLDER_NAMES"

      - name: Update ReadMe
        run: |
          FOLDER_LIST="$FOLDER_NAMES"
          OLD_CONTENT=$(curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.v3.raw" -s https://api.github.com/repos/${{ github.repository }}/contents/README.md)
          NEW_CONTENT=$(echo -e "$OLD_CONTENT" | sed -n '/## Solved LeetCode Problems/,$!p; /## Solved LeetCode Problems/,$s/.*/'"$FOLDER_LIST"'/' | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X PUT -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Content-Type: application/json" -d '{"message":"Update README with folder names", "content":"'"$(echo -n "$NEW_CONTENT" | base64)"'", "sha":"'"$(echo "$OLD_CONTENT" | curl -s https://api.github.com/repos/${{ github.repository }}/contents/README.md | jq -r .sha)"'"}' https://api.github.com/repos/${{ github.repository }}/contents/README.md
      

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent commits"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
