name: Update ReadMe with Commits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Folder Names
        id: folder_names
        run: |
          folder_list=$(python get_folders.py)
          echo "::set-output name=names::$folder_list"

      - name: Show Folder Names
        run: |
          echo "Folder names: ${{ steps.folder_names.outputs.names }}"

      - name: Get Previously Added Folders
        id: get_previous_folders
        run: |
          echo "PREVIOUS_FOLDERS=$(curl -H 'Authorization: token ${{ secrets.PAT_TOKEN }}' -H 'Accept: application/vnd.github.v3.raw' -s https://api.github.com/repos/${{ github.repository }}/contents/README.md | sed -n '/## Solved LeetCode Problems/,$!p; /## Solved LeetCode Problems/,$s/.*- \(.*\)/\1/p' | sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_ENV

      - name: Update ReadMe with New Folders
        run: |
          PREVIOUS_FOLDERS="${{ env.PREVIOUS_FOLDERS }}"
          FOLDER_LIST="${{ steps.folder_names.outputs.names }}"
          NEW_FOLDERS=$(echo "$FOLDER_LIST" | grep -v -F "$PREVIOUS_FOLDERS")
          if [ -n "$NEW_FOLDERS" ]; then
            NEW_CONTENT=$(echo "$NEW_FOLDERS" | awk '{print "- " $0}')
            OLD_CONTENT=$(curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.v3.raw" -s https://api.github.com/repos/${{ github.repository }}/contents/README.md)
            NEW_CONTENT=$(echo -e "$OLD_CONTENT\n\n## Solved LeetCode Problems\n$NEW_CONTENT" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
            PAYLOAD="{\"message\":\"Update README with folder names\",\"content\":\"$NEW_CONTENT\",\"sha\":\"$(echo "$OLD_CONTENT" | curl -s https://api.github.com/repos/${{ github.repository }}/contents/README.md | jq -r .sha)\"}"
            curl -X PUT -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Content-Type: application/json" -d "$PAYLOAD" https://api.github.com/repos/${{ github.repository }}/contents/README.md
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent commits"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
